# Project information
site_name: Data Science Interview preparation
site_author: Kuldeep Singh Sidhu
site_description: >-
  This is a completely open-source platform for
  maintaining curated list of interview questions
  and answers for people looking and preparing
  for data science opportunities.

# Repository
repo_name: singhsidhukuldeep/data-science-interview-prep
repo_url: https://github.com/singhsidhukuldeep/data-science-interview-prep

extra:
  social:
    - icon: octicons/mark-github-16
      link: https://github.com/singhsidhukuldeep/
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/singhsidhukuldeep
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/u/7182350/
    - icon: octicons/globe-16
      link: http://kuldeepsinghsidhu.com
    - icon: fontawesome/brands/git-alt
      link: https://github.com/singhsidhukuldeep/data-science-interview-prep
theme:
  name: material
#  features:
#    - tabs
#    - instant
  icon:
    logo: fontawesome/solid/terminal
    repo: fontawesome/brands/git-alt
#  favicon: fontawesome/solid/terminal
  palette:
    scheme: default
    primary: black
    accent: purple

#plugins
plugins:
  - search:
      lang:
        - en
  - git-revision-date-localized:
      type: date
  - minify:
      minify_html: true

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - meta
  - codehilite

# Page tree
nav:
  - ğŸ¡ Home: index.md

  - ğŸ“… Suggested Learning Paths: Suggested-Learning-Paths.md

  - ğŸ‘¨ğŸ¾â€ğŸ’» Online Resources:
      - Online Study Material: Online-Material/Online-Material-for-Learning.md
      - Popular Blogs: Online-Material/popular-resouces.md

  - ğŸš´ğŸ½â€â™€ As fast as possible:
      - Introduction: as-fast-as-possible/index.md
      - Neural Networks: as-fast-as-possible/Neural-Networks.md
      - Deep Natural Language Processing: as-fast-as-possible/Deep-NLP.md
      - Deep Computer Vision: as-fast-as-possible/Deep-CV.md
      - Tensorflow 2 with Keras: as-fast-as-possible/TF2-Keras.md

  - â€ğŸ“ ML Topics:
      - Machine-Learning\ARIMA.md
      - Machine-Learning\Activation functions.md
      - Machine-Learning\Collaborative Filtering.md
      - Machine-Learning\Confusion Matrix.md
      - Machine-Learning\DBSCAN.md
      - Machine-Learning\Decision Trees.md
      - Machine-Learning\Gradient Boosting.md
      - Machine-Learning\K-means clustering.md
      - Machine-Learning\Linear Regression.md
      - Machine-Learning\Logistic Regression.md
      - Machine-Learning\Loss Function MAE, RMSE.md
      - Machine-Learning\Neural Networks.md
      - Machine-Learning\Normal Distribution.md
      - Machine-Learning\Normalization Regularisation.md
      - Machine-Learning\Overfitting, Underfitting.md
      - Machine-Learning\PCA.md
      - Machine-Learning\Random Forest.md
      - Machine-Learning\Support Vector Machines.md
      - Machine-Learning\Unbalanced, Skewed data.md
      - Machine-Learning\kNN.md

  - ğŸ“ Cheat Sheets:
      - Python: Cheat-Sheets/Python.md
      - NumPy: Cheat-Sheets/NumPy.md
      - Pandas: Cheat-Sheets/Pandas.md
      - Scikit Learn: Cheat-Sheets/Sk-learn.md
      - Keras: Cheat-Sheets/Keras.md
      - PyTorch: Cheat-Sheets/PyTorch.md
      - TensorFlow: Cheat-Sheets/tensorflow.md
      - SQL: Cheat-Sheets/SQL.md
      - Regular Expressions (RegEx): Cheat-Sheets/RegEx.md
      - Flask: Cheat-Sheets/Flask.md
      - Django: Cheat-Sheets/Django.md
      - PySpark: Cheat-Sheets/PySpark.md

  - ğŸŒ Deploying ML Models:
      - Production Deployment: Deploying-ML-models/deploying-ml-models.md

  - ğŸ‘¨ğŸ¿â€ğŸ« Interview Questions:
      - Natural Language Processing (NLP): Interview-Questions/Natural-Language-Processing.md
      - Probability: Interview-Questions/Probability.md

  - ğŸ“³ Projects: projects.md

# Copyright
copyright: Copyright &copy; 2020 - 2021 <strong>Kuldeep Singh Sidhu</strong>
