# Project information
site_name: Data Science Interview preparation
site_author: Kuldeep Singh Sidhu
site_description: >-
  This is a completely open-source platform for
  maintaining curated list of interview questions
  and answers for people looking and preparing
  for data science opportunities.

# Repository
repo_name: singhsidhukuldeep/singhsidhukuldeep.github.io
repo_url: https://github.com/singhsidhukuldeep/singhsidhukuldeep.github.io

# extra_javascript:
#   - 'javascripts/xfile.js'
extra_css:
  - 'stylesheets/extra.css'
extra:
  generator: false

  social:
    - icon: octicons/mark-github-16
      link: https://github.com/singhsidhukuldeep/
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/singhsidhukuldeep
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/kuldeep_s_s
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/u/7182350/
    - icon: hf-logo-pirate
      link: https://huggingface.co/singhsidhukuldeep
    - icon: octicons/globe-16
      link: http://kuldeepsinghsidhu.com

  analytics:
    provider: google
    property: G-EVGNTG49J7

  # consent:
  #   title: Cookie Consent <br><small>Help Us âœŒï¸, Help You ğŸ«µ</small>
  #   actions:
  #     - accept
  #     - manage
  #   cookies:
  #     analytics:
  #       name: Google
  #       checked: true
  #     github:
  #       name: GitHub
  #       checked: true
  #   description: >- 
  #     We use cookies to recognize your repeated visits and preferences, improve and offer better servicesğŸ¤—
  #     <br>
  #     With your consentğŸ¤, you're helping us to give you better experience. 
  #     <br>
  #     <a herf="https://singhsidhukuldeep.github.io/privacy">Read about privacy policy here<a>

theme:
  name: material
  custom_dir: overrides

  features:
    # - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
    - content.tooltips
    - navigation.instant.progress
    - navigation.path
    - navigation.top

  icon:
    logo: fontawesome/solid/terminal
    repo: fontawesome/brands/git-alt
#  favicon: fontawesome/solid/terminal

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      accent: purple
      scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep purple
      accent: purple
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
#plugins
plugins:
  # - optimize
  - enumerate-headings:
        toc_depth: 6
        strict: true
        increment_across_pages: false
        include:
          - "Interview-Questions/*"
          - "Cheat-Sheets/*"
        exclude:
          - "Interview-Questions/Interview-Questions.md"
        #   - another_page.md
        restart_increment_after:
          - Interview-Questions/*"
  - search:
      lang:
        - en
  # - privacy:
      # cache: false
  - git-revision-date-localized:
      type: date
  - minify:
      minify_html: true
  - mkdocs-jupyter: #https://github.com/danielfrg/mkdocs-jupyter
      execute: false
  - with-pdf:
      enabled_if_env: ENABLE_PDF_EXPORT
      cover_logo: https://repository-images.githubusercontent.com/275878203/13719500-bb75-11ea-8f3a-be2ffb87a6a2
      copyright: Copyright Â© 2020 - 2024 Kuldeep Singh Sidhu
      cover_title: The Data Science Book
      cover_subtitle: https://singhsidhukuldeep.github.io
      output_path: /workspace/singhsidhukuldeep.github.io/pdf_output/DataScience.pdf
      back_cover: true

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - meta
  - codehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Page tree
nav:
  - ğŸ¡ Home: index.md

  # - ğŸ˜¬ Introduction: Introduction.md

  # - ğŸ“… Suggested Learning Paths: Suggested-Learning-Paths.md

  - ğŸ‘¨ğŸ¿â€ğŸ« Interview Questions: 
      # - ğŸ‘¨ğŸ¿â€ğŸ« Interview Questions: Interview-Questions/Interview-Questions.md
      - DSA (Data Structures & Algorithms): Interview-Questions/data-structures-algorithms.md
      - System Design: Interview-Questions/System-design.md
      - Natural Language Processing (NLP): Interview-Questions/Natural-Language-Processing.md
      - Probability: Interview-Questions/Probability.md
  
  - ğŸ“ Cheat Sheets:
      - Django: Cheat-Sheets/Django.md
      - Flask: Cheat-Sheets/Flask.md
      - Hypothesis Tests: Cheat-Sheets/Hypothesis-Tests.md
      - Keras: Cheat-Sheets/Keras.md
      - NumPy: Cheat-Sheets/NumPy.ipynb
      - Pandas: Cheat-Sheets/Pandas.md
      - PySpark: Cheat-Sheets/PySpark.md
      - PyTorch: Cheat-Sheets/PyTorch.md
      - Python: Cheat-Sheets/Python.md
      - Regular Expressions (RegEx): Cheat-Sheets/RegEx.md
      - Scikit Learn: Cheat-Sheets/Sk-learn.md
      - SQL: Cheat-Sheets/SQL.md
      - TensorFlow: Cheat-Sheets/tensorflow.md

  - â€ğŸ“ ML Topics:
      - ARIMA: Machine-Learning\ARIMA.md
      - Activation functions: Machine-Learning\Activation functions.md
      - Collaborative Filtering: Machine-Learning\Collaborative Filtering.md
      - Confusion Matrix: Machine-Learning\Confusion Matrix.md
      - DBSCAN: Machine-Learning\DBSCAN.md
      - Decision Trees: Machine-Learning\Decision Trees.md
      - Gradient Boosting: Machine-Learning\Gradient Boosting.md
      - K-means clustering: Machine-Learning\K-means clustering.md
      - Linear Regression: Machine-Learning\Linear Regression.md
      - Logistic Regression: Machine-Learning\Logistic Regression.md
      - Loss Function MAE, RMSE: Machine-Learning\Loss Function MAE, RMSE.md
      - Neural Networks: Machine-Learning\Neural Networks.md
      - Normal Distribution: Machine-Learning\Normal Distribution.md
      - Normalization Regularisation: Machine-Learning\Normalization Regularisation.md
      - Overfitting, Underfitting: Machine-Learning\Overfitting, Underfitting.md
      - PCA: Machine-Learning\PCA.md
      - Random Forest: Machine-Learning\Random Forest.md
      - Support Vector Machines: Machine-Learning\Support Vector Machines.md
      - Unbalanced, Skewed data: Machine-Learning\Unbalanced, Skewed data.md
      - kNN: Machine-Learning\kNN.md

  - ğŸ‘¨ğŸ¾â€ğŸ’» Online Resources:
      - Online Study Material: Online-Material/Online-Material-for-Learning.md
      - Popular Blogs: Online-Material/popular-resources.md

  # - ğŸš´ğŸ½â€â™€ As fast as possible:
  #     - Introduction: as-fast-as-possible/index.md
  #     - Neural Networks: as-fast-as-possible/Neural-Networks.md
  #     - Deep Natural Language Processing: as-fast-as-possible/Deep-NLP.md
  #     - Deep Computer Vision: as-fast-as-possible/Deep-CV.md
  #     - Tensorflow 2 with Keras: as-fast-as-possible/TF2-Keras.md

  # - ğŸŒ Deploying ML Models:
  #     - Production Deployment: Deploying-ML-models/deploying-ml-models.md

  - ğŸ“³ Projects: projects.md

  - ğŸ¤ Contribute: Contribute.md

  - <small>Privacy Policy</small>: privacy.md
  - <small>Contact</small>: contact.md

# Copyright
copyright: >-
  Copyright &copy; 2020 - 
  <script>document.write(/\d{4}/.exec(Date())[0])</script>
  â€¢ <strong>Kuldeep Singh Sidhu</strong>
  â€¢ <u><a href="https://choosealicense.com/licenses/agpl-3.0/" target=â€_blankâ€>License</a></u> 
  â€¢ <u><a href="/privacy">Privacy Policy</a></u> â€¢ <u><a href="/contact">Contact</a></u> 
  â€¢